Repository webjump/magento2-module-braspagpagador, pull requests merged in 2019-02, with the labels that each got.

#48 Change return array to return mixed because is causing errors
  Api/InstallmentsInterface.php
Labels: bug

#52 PACTV-809 fixing incorrect address information error of the orders
  Gateway/Transaction/CreditCard/Resource/Authorize/Request.php
  Gateway/Transaction/CreditCard/Resource/Authorize/RequestBuilder.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Authorize/RequestBuilderTest.php
  etc/di.xml
Labels: bug

#53 Created validation when invoice integration fail
  Gateway/Transaction/CreditCard/Command/CaptureCommand.php
  Gateway/Transaction/CreditCard/Resource/Capture/Response/Validator.php
  Test/Unit/Gateway/Transaction/CreditCard/Command/CaptureCommandTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Authorize/Response/ValidatorTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Capture/Response/ValidatorTest.php
  etc/di.xml
Labels: bug, enhancement

#54 Add a lookup to customer identity to verify the attribute in quote billing address and if it fails in quote
  Gateway/Transaction/Billet/Resource/Send/Request.php
  Gateway/Transaction/CreditCard/Resource/Authorize/Request.php
  etc/adminhtml/system/customer.xml
  etc/config.xml
Labels: bug, enhancement

#55 Added installments option for credit card on admin session
  Block/Form/CreditCard.php
  Gateway/Transaction/Base/Resource/Installments/Builder.php
  Test/Unit/Block/Form/CreditCardTest.php
  Test/Unit/Gateway/Transaction/Base/Resource/Installments/BuilderTest.php
  view/adminhtml/templates/form/credit-card.phtml
Labels: enhancement

#56 Get store scope config when antifraud capture the invoice
  Gateway/Transaction/Base/Config/Config.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
Labels: bug
