Repository webjump/magento2-module-braspagpagador, pull requests merged in 2019-07, with the labels that each got.

#66 Fixed count method use and import generic exception
  Block/Payment/Info/CreditCard.php
  Model/CardTokenManager.php
Labels: bug

#70 Get table name with default prefix
  Setup/UpgradeSchema.php
Labels: bug

#76 Release/3.8.0 - Authentication 3DS 2.0
  Setup/UpgradeSchema.php
Labels: enhancement

#77 BPAG-95 - Fix Capture and Anti Fraud Notifications.
  Gateway/Transaction/CreditCard/Resource/AntiFraud/Items/Request.php
  Gateway/Transaction/CreditCard/Resource/AntiFraud/Request.php
  Gateway/Transaction/CreditCard/Resource/Avs/Request.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
Labels: bug

#78 Hotfix/3.8.2 - Fix order cancel after authorize, clean customer name string and Fix offline invoice after authorize
  Gateway/Transaction/Base/Command/InitializeCommand.php
  Gateway/Transaction/Billet/Resource/Send/Request.php
  Gateway/Transaction/CreditCard/Resource/AntiFraud/MDD/AbstractMDD.php
  Gateway/Transaction/CreditCard/Resource/AntiFraud/MDD/GeneralRequest.php
  Gateway/Transaction/CreditCard/Resource/Authorize/Request.php
  Gateway/Transaction/DebitCard/Resource/Order/Request.php
  Helper/Data.php
  Model/Source/BilletTypes.php
  Model/Source/Status/Review.php
  Observer/CheckoutSubmitAllAfterObserver.php
  Test/Unit/Gateway/Transaction/Billet/Resource/Send/RequestTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/AntiFraud/MDD/GeneralRequestTest.php
  Test/Unit/Gateway/Transaction/DebitCard/Resource/Order/RequestTest.php
  Test/Unit/Model/Source/BilletTypesTest.php
  etc/events.xml
Labels: bug

#79 Hotfix/3.8.3 - Create new payment type, fix cielo restriction validator in test mode and fix customer identify
  Gateway/Transaction/Billet/Resource/Send/Request.php
  Gateway/Transaction/CreditCard/Resource/Authorize/Request.php
  Gateway/Transaction/CreditCard/Resource/Authorize/Request/Validator.php
  Gateway/Transaction/DebitCard/Resource/Order/Request/Validator.php
  Helper/Data.php
  Model/Source/Cctype.php
  Model/Source/Dctype.php
  Test/Unit/Model/Source/CCTypeTest.php
  Test/Unit/Model/Source/DctypeTest.php
  etc/payment.xml
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/debitcard.js
Labels: bug, enhancement
