Repository webjump/magento2-module-braspagpagador, pull requests merged in 2021-08, with the labels that each got.

#180 Feature/split updates
  Block/Adminhtml/PaymentSplit/Edit/Tab/Items.php
  Block/Adminhtml/PaymentSplit/Edit/Tab/Main.php
  Block/Adminhtml/PaymentSplit/Grid.php
  Block/Adminhtml/PaymentSplit/Grid/Renderer.php
  Controller/Adminhtml/PaymentSplit/AbstractPaymentSplit.php
  Controller/Adminhtml/PaymentSplit/Save.php
  Cron/PaymentSplitTransactionPost.php
  Gateway/Transaction/Base/Resource/Void/RequestBuilder.php
  Gateway/Transaction/Boleto/Config/Config.php
  Gateway/Transaction/Boleto/Config/ConfigInterface.php
  Gateway/Transaction/CreditCard/Config/Config.php
  Gateway/Transaction/CreditCard/Config/ConfigInterface.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request/SplitHandler.php
  Gateway/Transaction/CreditCard/Resource/Capture/RequestBuilder.php
  Gateway/Transaction/DebitCard/Config/Config.php
  Gateway/Transaction/DebitCard/Config/ConfigInterface.php
  Model/SplitManager.php
  Setup/UpgradeSchema.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/EditTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/ExportCsvTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/ExportXmlTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/GridTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/IndexTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/SaveTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/SendTransationalPostTest.php
  Test/Unit/Cron/PaymentSplitTransactionPostTest.php
  Test/Unit/Gateway/Transaction/Boleto/Config/ConfigTest.php
  Test/Unit/Gateway/Transaction/Boleto/Resource/Send/RequestTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Config/ConfigTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Authorize/RequestTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Capture/RequestTest.php
  Test/Unit/Gateway/Transaction/DebitCard/Config/ConfigTest.php
  composer.json
  etc/adminhtml/system/transaction/boleto/paymentsplit.xml
  etc/adminhtml/system/transaction/creditcard/paymentsplit.xml
  etc/adminhtml/system/transaction/debitcard/paymentsplit.xml
  etc/di.xml
  etc/module.xml
Labels: bug, enhancement

#181 Develop
  Block/Adminhtml/PaymentSplit/Edit/Tab/Items.php
  Block/Adminhtml/PaymentSplit/Edit/Tab/Main.php
  Block/Adminhtml/PaymentSplit/Grid.php
  Block/Adminhtml/PaymentSplit/Grid/Renderer.php
  Controller/Adminhtml/PaymentSplit/AbstractPaymentSplit.php
  Controller/Adminhtml/PaymentSplit/Save.php
  Cron/PaymentSplitTransactionPost.php
  Gateway/Transaction/Base/Resource/Void/RequestBuilder.php
  Gateway/Transaction/Boleto/Config/Config.php
  Gateway/Transaction/Boleto/Config/ConfigInterface.php
  Gateway/Transaction/CreditCard/Config/Config.php
  Gateway/Transaction/CreditCard/Config/ConfigInterface.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request/SplitHandler.php
  Gateway/Transaction/CreditCard/Resource/Capture/RequestBuilder.php
  Gateway/Transaction/DebitCard/Config/Config.php
  Gateway/Transaction/DebitCard/Config/ConfigInterface.php
  Model/SplitManager.php
  Setup/UpgradeSchema.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/EditTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/ExportCsvTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/ExportXmlTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/GridTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/IndexTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/SaveTest.php
  Test/Unit/Controller/Adminhtml/PaymentSplit/SendTransationalPostTest.php
  Test/Unit/Cron/PaymentSplitTransactionPostTest.php
  Test/Unit/Gateway/Transaction/Boleto/Config/ConfigTest.php
  Test/Unit/Gateway/Transaction/Boleto/Resource/Send/RequestTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Config/ConfigTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Authorize/RequestTest.php
  Test/Unit/Gateway/Transaction/CreditCard/Resource/Capture/RequestTest.php
  Test/Unit/Gateway/Transaction/DebitCard/Config/ConfigTest.php
  composer.json
  etc/adminhtml/system/transaction/boleto/paymentsplit.xml
  etc/adminhtml/system/transaction/creditcard/paymentsplit.xml
  etc/adminhtml/system/transaction/debitcard/paymentsplit.xml
  etc/di.xml
  etc/module.xml
Labels: bug, enhancement

#182 Fix Split Webkul Items
  Gateway/Transaction/Boleto/Config/Config.php
  Gateway/Transaction/Boleto/Config/ConfigInterface.php
  Gateway/Transaction/Boleto/Resource/PaymentSplit/Request.php
  Gateway/Transaction/Boleto/Resource/Send/Request.php
  Gateway/Transaction/Boleto/Resource/Send/RequestBuilder.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
  Model/SplitManager.php
  composer.json
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/debitcard.js
Labels: bug, enhancement

#183 Develop
  Gateway/Transaction/Boleto/Config/Config.php
  Gateway/Transaction/Boleto/Config/ConfigInterface.php
  Gateway/Transaction/Boleto/Resource/PaymentSplit/Request.php
  Gateway/Transaction/Boleto/Resource/Send/Request.php
  Gateway/Transaction/Boleto/Resource/Send/RequestBuilder.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
  Model/SplitManager.php
  composer.json
  view/frontend/web/js/view/payment/method-renderer/creditcard.js
  view/frontend/web/js/view/payment/method-renderer/debitcard.js
Labels: bug, enhancement

#184 update payment split and fix braspag antifraude notification
  Block/Adminhtml/PaymentSplit/Edit/Tab/Main.php
  Block/Adminhtml/PaymentSplit/Grid.php
  Gateway/Transaction/Boleto/Resource/Send/Response/SplitHandler.php
  Gateway/Transaction/CreditCard/Resource/Authorize/Response/SplitHandler.php
  Gateway/Transaction/CreditCard/Resource/Capture/Response/SplitHandler.php
  Gateway/Transaction/DebitCard/Resource/Order/Response/SplitHandler.php
  Gateway/Transaction/PaymentSplit/Resource/TransactionPost/Response/TransactionPostSplitHandler.php
  Model/NotificationManager.php
  Model/SplitDataAdapter.php
  Model/SplitDataProvider.php
  Model/SplitManager.php
  Setup/UpgradeSchema.php
  composer.json
  etc/module.xml
Labels: enhancement

#185 Develop
  Block/Adminhtml/PaymentSplit/Edit/Tab/Main.php
  Block/Adminhtml/PaymentSplit/Grid.php
  Gateway/Transaction/Boleto/Resource/Send/Response/SplitHandler.php
  Gateway/Transaction/CreditCard/Resource/Authorize/Response/SplitHandler.php
  Gateway/Transaction/CreditCard/Resource/Capture/Response/SplitHandler.php
  Gateway/Transaction/DebitCard/Resource/Order/Response/SplitHandler.php
  Gateway/Transaction/PaymentSplit/Resource/TransactionPost/Response/TransactionPostSplitHandler.php
  Model/NotificationManager.php
  Model/SplitDataAdapter.php
  Model/SplitDataProvider.php
  Model/SplitManager.php
  Setup/UpgradeSchema.php
  composer.json
  etc/module.xml
Labels: enhancement

#187 Develop
  Api/SplitManagerInterface.php
  Gateway/Transaction/Boleto/Resource/Send/Request.php
  Gateway/Transaction/CreditCard/Resource/Capture/Request.php
  Gateway/Transaction/CreditCard/Resource/Capture/RequestBuilder.php
  Gateway/Transaction/PaymentSplit/Resource/TransactionPost/Request/TransactionPostSplitHandler.php
  Helper/Data.php
  Model/SplitDataAdapter.php
  Model/SplitManager.php
  composer.json
Labels: enhancement

#188 Fix braspag order notification cancel after status changed in braspag
  Model/NotificationManager.php
Labels: enhancement

#189 Develop
  Model/NotificationManager.php
Labels: enhancement

#190 fix order cancel after notification
  Model/NotificationManager.php
Labels: bug

#191 Develop
  Model/NotificationManager.php
Labels: bug
